### ISSUE TITLE
Front-end: Display data

### ISSUE THREAD

**Issue by AmirHadjihabib** [codeforamerica/somerville-teacher-tool#29]
##### Description:
A visual layout of the Demographic and MCAS information. 

##### User story:
As a teacher, I want to view my students data organized so I can understand the information being displayed.

##### Phase 1:
* [x] I see data labeled with warnings.
* [x] I see students grouped by risk level.
* [x] I see headers for column groups e.g., Demographics.
* [x] I see headers for columns, e.g., Race, SPED, LEP.

##### Design:
http://invis.io/RW2MNTCVK

![roster phase 1 - home](https://cloud.githubusercontent.com/assets/4615904/7013162/ef26c0b4-dc6b-11e4-8d24-12ee88694684.png)

**Comment by alexsoble** [comment]
ToDo: 

+ [ ] Incorporate STAR data into roster view

**Comment by alexsoble** [comment]
We're there! 

## Gif: 
![star-mcas-select](https://cloud.githubusercontent.com/assets/3209501/7355042/358bdc6a-ecd4-11e4-8e81-f4e101ffe1d1.gif)
