### ISSUE TITLE
Front-end: Sort data

### ISSUE THREAD

**Issue by AmirHadjihabib** [codeforamerica/somerville-teacher-tool#36]
##### Description:
A way to select the columns being displayed.

##### User story:
As a teacher, I want to select the information to be displayed so I can see what is important to me at the time.

##### Phase 1:
* [ ] I see a list of selectable columns groups.
* [ ] I see a list of selectable columns.
* [ ] I can select a column group to hide or show.
* [ ] I can select a column to hide or show.

##### Design:
https://projects.invisionapp.com/share/RW2MNTCVK#/screens/71720400?maintainScrollPosition=true

![roster phase 1 - column](https://cloud.githubusercontent.com/assets/4615904/7013292/d78b4ce4-dc6c-11e4-935f-e56af1f560fb.png)

**Comment by marimuraki** [comment]
Updates under "Demographics":

- "ELL" == LEP"
-  "FLRP" -> "FRPL"

Include new assessment - STAR (Math & Reading):
- PR = percentile rank
- IRL = instructional reading level (Reading only)
