### ISSUE TITLE
Improve roster view

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#59]
From our April 27 call with the wonderful Healey teacher team: 

"can we filter by different demographics?
"flexibility to group by demographics and performance levels"

**Comment by AmirHadjihabib** [comment]
We have this design from before. Not sure if we want to revisit it or work on a new concept.

https://github.com/codeforamerica/somerville-teacher-tool/issues/36

![screen shot 2015-04-27 at 10 42 38 am](https://cloud.githubusercontent.com/assets/4615904/7353670/3e7746ca-ecca-11e4-9aa2-f41e78c13ef9.png)

**Comment by alexsoble** [comment]
I'm thinking a little different. As I understand it, the checkmarks in the drop-down above would show/hide different columns of data. What about a "sort" function that reorders the rows according to whichever group the teacher is interested in? Something like this: http://tristen.ca/tablesort/demo/

**Comment by AmirHadjihabib** [comment]
I like it. Maybe something like this with dynamic grouping headers? 

![screen shot 2015-04-27 at 11 13 53 am](https://cloud.githubusercontent.com/assets/4615904/7354205/83c94256-ecce-11e4-946c-5073d653136c.png)

**Comment by jsgeiser** [comment]
Yes - on the right track with a 'sort' function. We do want to be able to filter out columns as needed. We also would like to move data around to look at it from different angles and to have the flexibility to group students as need. Then if we could take data from a table and turn it into a graph, chart, etc. that would help us get a visual of trends/movement of data. 

Thanks for your work on this! It is seriously taking shape!

**Comment by alexsoble** [comment]
### Roster Current Status GIF
![star-mcas-select-3](https://cloud.githubusercontent.com/assets/3209501/7491972/0c5c9fe2-f3bd-11e4-927d-63b7c286889a.gif)

### ToDo:

+ [ ] Add red warning dots to MCAS Warning results only for now as per conversation with @marimuraki and @AmirHadjihabib
+ [ ] Get feedback from Healey team about:
  + [ ] if red warning dots are useful and if so,
  + [ ] which data items should get red warning dots
+ [ ] Blow away the risk analysis code, since the educator is doing her/his own risk sorting now

**Comment by alexsoble** [comment]
###  Warning labels that pop

![pop](https://cloud.githubusercontent.com/assets/3209501/7495216/87e0b35c-f3da-11e4-90cf-c8ab19d27687.png)

**Comment by alexsoble** [comment]
Feedback from Uri Harel on what should have a warning indicator: https://github.com/codeforamerica/somerville-teacher-tool/issues/52#issuecomment-99487128

**Comment by alexsoble** [comment]
Let's call this "Improve Roster" so that it encompasses warning labels and a legend as well as filtering/sorting. Then when it's done we'll turn to the student profile.

**Comment by alexsoble** [comment]
### Make your own view
![star-mcas-select-4](https://cloud.githubusercontent.com/assets/3209501/7515207/eb846f12-f492-11e4-831c-8799e3bc36fb.gif)

### Sort columns
![sort-sort-2](https://cloud.githubusercontent.com/assets/3209501/7515219/023c1ffc-f493-11e4-8fea-ecf708886ac1.gif)

### New look for warning bubbles
![lots-of-bubbles](https://cloud.githubusercontent.com/assets/3209501/7515150/670f6962-f492-11e4-8933-d53a10e652f7.png)

**Comment by jsgeiser** [comment]
I like having the ability to filter and sort. Would the interventions be listed here also (to see where interventions are concentrated relative to performance)?

**Comment by alexsoble** [comment]
Hi @jsgeiser! Showing interventions would absolutely be the next step. @AmirHadjihabib is putting together a design to show what that could look like.

**Comment by alexsoble** [comment]
@jsgeiser @AmirHadjihabib Created a new issue for this next piece: #87

**Comment by AmirHadjihabib** [comment]
@jsgeiser Here is a version with interventions both on the Roster and the Profile. It would be great to hear your thoughts. You can comment directly on the design. 

http://invis.io/TK2ZLZU97
Press "c" to comment and hold "shift" to see clickable areas. 

Thanks!
