### ISSUE TITLE
Front-end: Display student profile 

### ISSUE THREAD

**Issue by AmirHadjihabib** [codeforamerica/somerville-teacher-tool#63]
##### Description:
A visual display of current and historical information for a single student.

##### User story:
As a teacher, I want to view current and historical data for a single student so I can have a better holistic understanding of that student.

##### Phase 1:
Overview of student
* [x] I see the student's name
* [x] I see the student's contact information
* [x] I see the student's demographics

For current and past years
* [x] I see the student's attendance information (absence and tardies)
* [x] I see the student's behavioral information (suspension and expulsion) 
* [x] I see the student's office referral information (when and why)
* [x] I see the student's assessment information (MCAS and STAR) 

##### Design:
Phase 1 MVP:
http://invis.io/SZ2TLEAWK

Vision:
http://invis.io/4E2TLEL5V

![student profile v2 mvp](https://cloud.githubusercontent.com/assets/4615904/7354417/39781810-ecd0-11e4-9fa7-5e6cdcf353e3.png)

**Comment by marimuraki** [comment]
Teacher comment: "Hard to see because I have to scroll down ..." --- want to be able to see year-to-year historical data for a student in one box

**Comment by AmirHadjihabib** [comment]
Current version:
http://invis.io/G62VVOJME

![student profile v6](https://cloud.githubusercontent.com/assets/4615904/7539609/0536cb2e-f55d-11e4-886b-9f903dbec8fb.png)
